name: 'cloudrun-action'
description: 'Deploy a Docker Image using Google Cloud Run'
author: 'Rick van den Hof'
inputs:
  name:
    required: true
    description: 'Name of the service'
  image:
    required: true
    description: 'Image to run on Google Cloud Run'
outputs:
  url:
    description: 'The URL assigned by Google Cloud Run to the service'
runs:
  using: 'node12'
  main: 'dist/index.js'
